# Generated by Django 3.2.7 on 2022-01-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='crs_descrption',
            new_name='course_description',
        ),
        migrations.RenameField(
            model_name='course_details',
            old_name='crs_img',
            new_name='course_img',
        ),
        migrations.RenameField(
            model_name='course_details',
            old_name='crs_price',
            new_name='course_price',
        ),
        migrations.RenameField(
            model_name='course_details',
            old_name='crs_title',
            new_name='course_title',
        ),
        migrations.RenameField(
            model_name='course_details',
            old_name='std_no',
            new_name='student_no',
        ),
        migrations.RenameField(
            model_name='course_details',
            old_name='usr_img',
            new_name='user_img',
        ),
        migrations.RenameField(
            model_name='course_details',
            old_name='usr_name',
            new_name='user_name',
        ),
    ]
