# Generated by Django 3.2.7 on 2022-01-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20220113_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_details',
            new_name='course_detail',
        ),
    ]
