# Generated by Django 3.2.7 on 2022-01-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('course', '0003_rename_course_details_course_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_detail',
            name='user_img',
        ),
        migrations.RemoveField(
            model_name='course_detail',
            name='user_name',
        ),
        migrations.AddField(
            model_name='course_detail',
            name='course_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_detail', to='user_profile.instructor'),
        ),
    ]
