# Generated by Django 3.2.7 on 2022-01-18 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220118_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_detail',
            old_name='course_duration',
            new_name='course_duration_in_weeks',
        ),
    ]
