# Generated by Django 3.2.7 on 2022-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_crs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='who_this_course',
            field=models.TextField(null=True),
        ),
    ]
