# Generated by Django 3.2.7 on 2022-01-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_detail_who_this_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crs_review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crs_review',
            name='website',
        ),
    ]
