# Generated by Django 3.2.7 on 2022-01-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20220119_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
