# Generated by Django 3.2.7 on 2022-01-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_instructor_slug'),
        ('course', '0011_alter_course_detail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_certificate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_duration_in_weeks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_detail', to='user_profile.instructor'),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_quiz',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='who_this_course',
            field=models.TextField(),
        ),
    ]
