# Generated by Django 3.2.7 on 2022-01-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_for_which_crs_who_this_crs_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_detail',
            name='who_this_course',
        ),
    ]
