# Generated by Django 3.2.7 on 2022-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_course_detail_who_this_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='who_this_course',
            field=models.ManyToManyField(to='course.who_this_crs_for'),
        ),
        migrations.DeleteModel(
            name='for_which_crs',
        ),
    ]
