# Generated by Django 3.2.7 on 2022-01-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20220128_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='YT_video_url',
            field=models.URLField(blank=True),
        ),
    ]
