# Generated by Django 3.2.7 on 2022-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_course_detail_yt_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='course_certificate',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_duration_in_weeks',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='course_quiz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_detail',
            name='lession_no',
            field=models.IntegerField(blank=True),
        ),
    ]
