# Generated by Django 3.2.7 on 2022-01-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20220128_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='lession_no',
            field=models.IntegerField(default=0),
        ),
    ]
