# Generated by Django 3.2.7 on 2022-01-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_course_detail_lession_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='course_duration_in_weeks',
            field=models.IntegerField(default=0),
        ),
    ]
