# Generated by Django 3.2.7 on 2022-01-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_course_detail_who_this_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='course_img',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
