# Generated by Django 3.2.7 on 2022-01-29 05:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_course_detail_course_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='dec',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
