# Generated by Django 3.2.7 on 2022-02-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_alter_course_detail_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='course_certificate',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
