# Generated by Django 3.2.7 on 2022-02-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_course_detail_course_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_detail',
            name='dec',
        ),
    ]
