# Generated by Django 3.2.7 on 2022-02-03 12:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_remove_course_detail_dec'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_detail',
            name='short_course_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
