# Generated by Django 3.2.7 on 2022-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_course_detail_short_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_detail',
            name='course_img',
            field=models.ImageField(upload_to='image/course/'),
        ),
    ]
