# Generated by Django 3.2.7 on 2022-01-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdetail_element',
            name='blogs',
        ),
        migrations.RemoveField(
            model_name='blogdetail_img',
            name='blogs',
        ),
        migrations.AddField(
            model_name='blog_detail',
            name='blog_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_element', to='blog.blogdetail_element'),
        ),
        migrations.AddField(
            model_name='blog_detail',
            name='blog_imgs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_img', to='blog.blogdetail_img'),
        ),
    ]
