# Generated by Django 3.2.7 on 2022-01-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220118_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetail_element',
            old_name='imgs',
            new_name='element',
        ),
    ]
