# Generated by Django 3.2.7 on 2022-01-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_imgs_blogdetail_element_element'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_detail',
            old_name='blog_element',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='blog_detail',
            old_name='blog_imgs',
            new_name='imgs',
        ),
    ]
