# Generated by Django 3.2.7 on 2022-01-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220118_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_detail',
            old_name='head3',
            new_name='setting',
        ),
        migrations.RenameField(
            model_name='blog_detail',
            old_name='head4',
            new_name='why_need',
        ),
    ]
