# Generated by Django 3.2.7 on 2022-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220118_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_detail',
            name='slug',
            field=models.SlugField(max_length=1000, null=True),
        ),
    ]
