# Generated by Django 3.2.7 on 2022-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220120_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='blog_img',
            field=models.ImageField(upload_to='image/blog/'),
        ),
        migrations.AlterField(
            model_name='blogdetail_img',
            name='imgs',
            field=models.ImageField(upload_to='image/blog/'),
        ),
    ]
