# Generated by Django 3.2.7 on 2022-01-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_details',
            new_name='event_detail',
        ),
    ]
