# Generated by Django 3.2.7 on 2022-01-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_event_details_event_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_detail',
            name='about_event',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='event_booked_slot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='event_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='event_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='event_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='event_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='event_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='event_total_slot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event_detail',
            name='where_event',
            field=models.TextField(null=True),
        ),
    ]
