# Generated by Django 3.2.7 on 2022-01-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220115_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_detail',
            name='slug',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
