# Generated by Django 3.2.7 on 2022-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_detail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_detail',
            name='about_event',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='event_booked_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='event_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='event_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='event_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='event_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='event_start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='event_total_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='event_detail',
            name='where_event',
            field=models.TextField(),
        ),
    ]
