# Generated by Django 3.2.7 on 2022-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20220120_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_detail',
            name='event_img',
            field=models.ImageField(upload_to='image/event/'),
        ),
    ]
