# Generated by Django 3.2.7 on 2022-01-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=100)),
                ('quntity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='shop_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_img', models.ImageField(upload_to='')),
                ('shop_title', models.CharField(max_length=100)),
                ('shop_price', models.IntegerField()),
                ('about_shop', models.TextField(null=True)),
                ('shop_description', models.TextField(null=True)),
                ('shop_tag', models.CharField(max_length=100, null=True)),
                ('quntity', models.IntegerField(null=True)),
                ('shop_sku', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shop_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rate', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop_detail')),
            ],
        ),
    ]
