# Generated by Django 3.2.7 on 2022-01-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220118_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_order',
            name='quntity',
            field=models.IntegerField(null=True),
        ),
    ]
