# Generated by Django 3.2.7 on 2022-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220118_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_order',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
