# Generated by Django 3.2.7 on 2022-01-21 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_auto_20220120_1309'),
        ('shop', '0010_cart_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('quntity', models.IntegerField()),
                ('payment', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('order_notes', models.TextField(blank=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course_detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
