# Generated by Django 3.2.7 on 2022-01-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_detail_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
