# Generated by Django 3.2.7 on 2022-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_code',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
