# Generated by Django 3.2.7 on 2022-01-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_coupon_code_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.IntegerField(null=True),
        ),
    ]
