# Generated by Django 3.2.7 on 2022-01-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.IntegerField(default=0),
        ),
    ]
