# Generated by Django 3.2.7 on 2022-02-01 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='id',
        ),
        migrations.AddField(
            model_name='course_order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product_order',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
