# Generated by Django 3.2.7 on 2022-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_shop_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='product_img',
            field=models.ImageField(upload_to='image/shop/'),
        ),
    ]
