# Generated by Django 3.2.7 on 2022-01-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
