# Generated by Django 3.2.7 on 2022-01-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20220115_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='expert',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
