# Generated by Django 3.2.7 on 2022-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='youtube',
            field=models.URLField(null=True),
        ),
    ]
