# Generated by Django 3.2.7 on 2022-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20220121_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='expert',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
