# Generated by Django 3.2.7 on 2022-01-22 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frgt_pwd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frg_token', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
